$image = "bento/ubuntu-20.04-arm64"

Vagrant.configure("2") do |config|
  config.vm.box = $image
  config.vm.synced_folder "./.vagrant/synced/backups", "/home/vagrant/backups"

  config.vm.define "lab10" do |node|
    node.vm.hostname = "lab10"
    node.vm.provider "vmware_fusion" do |vm|
      vm.memory = 2048
      vm.cpus = 2
    end
    node.vm.provision "shell", path: "entrypoint.sh"
  end
end
